services:
  - type: web
    name: dolibarr-clock-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_bridge:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0